"""
Prompt engineering for Spurgeon-style RAG.

These prompts are carefully tuned to:
- Force grounding in retrieved context
- Evoke Spurgeon's voice without hallucinating his style
- Handle "I don't know" gracefully
- Support future multi-author queries
"""

from __future__ import annotations
from typing import List
from config import SYSTEM_PROMPT_NEUTRAL, USER_PROMPT_TEMPLATE


def get_system_prompt(author: str = "Charles Haddon Spurgeon", variant: str = "default") -> str:
    """Return the system prompt for the RAG assistant.

    Available variants:
        - "default": Normal, clear, modern AI assistant style (recommended)
        - "strict": Very strict about staying in context and citing sources
        - "concise": Shorter, more direct answers
    """
    base = SYSTEM_PROMPT_NEUTRAL

    if variant == "strict":
        base += """

ADDITIONAL STRICT RULES (Strict Variant):
- You MUST explicitly cite the exact sermon number and title for every major point.
- If even a small part of the answer is not directly supported by the context, clearly state the limitation.
- Never combine ideas from multiple sermons without attributing each piece.
"""

    elif variant == "concise":
        base += """

ADDITIONAL RULES (Concise Variant):
- Be significantly more concise.
- Prioritize the most important points.
- Use shorter sentences and avoid unnecessary explanations.
"""

    if author != "Charles Haddon Spurgeon":
        base = f"""You are a helpful AI assistant answering questions based on the writings of {author}.

Ground every claim strictly in the provided CONTEXT. Quote or closely paraphrase when possible.
If the context does not contain the answer, say so plainly and do not speculate.
Cite specific works by title when available.
"""

    return base


def build_user_prompt(question: str, context: str, author: str = "Charles Haddon Spurgeon") -> str:
    """Build the final user message with retrieved context."""
    return USER_PROMPT_TEMPLATE.format(question=question, context=context)


def format_context(nodes: List) -> str:
    """
    Turn retrieved LlamaIndex nodes into a clean, attributed context block.

    Each node is expected to have:
        - node.metadata["sermon_number"]
        - node.metadata["title"]
        - node.metadata["volume"]
        - node.metadata["primary_scripture"]
        - node.get_content()
    """
    blocks = []
    for i, node in enumerate(nodes, 1):
        meta = node.metadata or {}
        sermon_num = meta.get("sermon_number", "?")
        title = meta.get("title", "Untitled Sermon")
        vol = meta.get("volume")
        scripture = meta.get("primary_scripture", "")
        text = node.get_content().strip()

        header = f"[Sermon {sermon_num} — \"{title}\""
        if vol:
            header += f", Volume {vol}"
        if scripture:
            header += f" | Text: {scripture}"
        header += "]"

        blocks.append(f"{header}\n{text}\n")

    return "\n\n".join(blocks)


def build_chat_messages(question: str, context_nodes: List, chat_history: List = None, author: str = "Charles Haddon Spurgeon"):
    """
    Return messages in the format expected by LlamaIndex ChatEngine / LLM.
    Keeps system + recent history + current grounded question.
    """
    from llama_index.core.llms import ChatMessage, MessageRole

    messages = [
        ChatMessage(role=MessageRole.SYSTEM, content=get_system_prompt(author))
    ]

    if chat_history:
        messages.extend(chat_history[-6:])  # keep last 3 exchanges

    context_str = format_context(context_nodes)
    user_content = build_user_prompt(question, context_str, author)
    messages.append(ChatMessage(role=MessageRole.USER, content=user_content))

    return messages


# =============================================================================
# LLM-as-Judge Prompt for RAG Evaluation
# =============================================================================

RAG_JUDGE_PROMPT = """You are an expert evaluator of Retrieval-Augmented Generation (RAG) systems for theological content, specifically the sermons of Charles Haddon Spurgeon.

You will be given:
- The user's QUESTION
- The CONTEXT that was retrieved from the sermon database (excerpts with sermon numbers and titles)
- The ANSWER generated by the RAG system

Your task is to score the ANSWER on the following four dimensions (1-5 scale):

1. **Groundedness** (1-5)
   - 5 = Every claim is directly supported by the provided CONTEXT. No hallucinations.
   - 1 = The answer contains significant claims not present in the CONTEXT.

2. **Citation Quality** (1-5)
   - 5 = Clearly and accurately cites specific sermon numbers and titles when using material.
   - 1 = Makes claims without citing sources or cites incorrectly.

3. **Honesty / Humility** (1-5)
   - 5 = Appropriately admits when the retrieved context is insufficient ("I do not find...", "the sermons before me do not address...").
   - 1 = Overconfidently answers questions the context cannot support.

4. **Helpfulness & Pastoral Tone** (1-5)
   - 5 = The answer is pastorally warm, biblically rich, and useful in the style of Spurgeon.
   - 1 = Cold, unhelpful, or stylistically poor.

Output **only valid JSON** in this exact format (no extra text):

{
  "groundedness": <integer 1-5>,
  "citation_quality": <integer 1-5>,
  "honesty": <integer 1-5>,
  "helpfulness": <integer 1-5>,
  "overall_score": <float average of the four scores>,
  "reasoning": "<2-4 sentence explanation of the scores, with specific examples from the answer>"
}

Be strict but fair. If the answer hallucinates or fails to cite when it should, deduct points.
"""


def build_judge_prompt(question: str, context: str, answer: str) -> str:
    """Build the prompt for the LLM judge."""
    return f"""{RAG_JUDGE_PROMPT}

---

QUESTION:
{question}

---

RETRIEVED CONTEXT:
{context}

---

GENERATED ANSWER:
{answer}

---

Now evaluate the answer and output only the JSON object."""
